In [40]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from warnings import filterwarnings

plt.rc('font', family = 'AppleGothic')
filterwarnings('ignore')

df = pd.read_csv("dataset/sac_ver02.csv").query("`place`=='콘서트홀'")

df_pivot_all_raw = df.pivot_table(index=['seat_floor','seat_col'], columns=['seat_block','seat_num'], aggfunc='size', fill_value=0)
df_pivot_all_raw

seat_block             A                                               ...  \
seat_num              1    2    3    4    5    6    7    8    9    10  ...
seat_floor seat_col                                                    ...
1           1        371  363  427  370  425  395  430  475  573    0  ...
            2        317  412  362  395  367  459  404  517  500    0  ...
            3        404  389  476  403  497  472  517  529  624    0  ...
            4        392  404  400  427  415  459  471  497  585  629  ...
            5        406  362  401  419  418  463  517  462  566  557  ...
            6        354  393  418  484  436  488  488  487  553  636  ...
            7        390  392  435  439  444  471  492  481  550  582  ...
            8        347  380  350  463  417  474  428  492  420  575  ...
            9        400  359  399  406  490  401  484  445  483  491  ...
            10       367  402  373  460  406  488  401  499  446  565  ...
            11       423  372  428  404  487  396  479  458  472  499  ...
            12       369  406  371  394  405  431  419  471  466  459  ...
            13       376  396  432  392  469  445  427  442  483  450  ...
            14         0    0    0    0    0    0    0    0    0    0  ...
            15       429  373  488  423  565  511  560  477  730  728  ...
            16       414  381  426  405  446  388  450  424  480  496  ...
            17       368  406  340  431  388  424  385  467  397  493  ...
            18       421  432  405  459  374  464  400  446  437  522  ...
            19       351  429  377  441  398  496  428  506  437    0  ...
            20       382  445  356  455  414  452  449  547    0    0  ...
            21       363  423  369  452  401  498  464    0    0    0  ...
            22       461  356  439  395  429  448  524    0    0    0  ...
2          -1          0    0    0    0    0    0    0    0    0    0  ...
            1        535  456  448  449  529  450  572  491  509  466  ...
            2        375  451  364  431  410  459  431  494  389  502  ...
            3        446  394  425  349  437  397  443  406  418  385  ...
            4        391  464  410  477  363  423  374  452  397  406  ...
            5        436  371  415  429  461  360  434  388  411  403  ...
            6        429  441  392  417  372  374  380  397  391  374  ...
            7        490  394  431  418  469  400  461  447  481  411  ...
            8         79   64   49   53   43   59   99  133    0    0  ...
3          -1          0    0    0    0    0    0    0    0    0    0  ...
            1        346  386  343  410  429    0    0    0    0    0  ...
            2        328  288  301  339  354    0    0    0    0    0  ...
            3        319  327  308  318  347  415    0    0    0    0  ...
            4        338  284  314  321  323  314  367  400  419  376  ...
            5        314  316  316  289  365  361  355  354  414  332  ...
            6        382  394  389  383  438  400  394  430  471    0  ...
            7        364  465  392  487  460    0    0    0    0    0  ...
4           1          0    0    0    0    0    0    0    0    0    0  ...
            2          0    0    0    0    0    0    0    0    0    0  ...
            3          0    0    0    0    0    0    0    0    0    0  ...
            4          0    0    0    0    0    0    0    0    0    0  ...

seat_block             N
seat_num              6    7    8    9    10   11   12   13   14   15
seat_floor seat_col
1           1          0    0    0    0    0    0    0    0    0    0
            2          0    0    0    0    0    0    0    0    0    0
            3          0    0    0    0    0    0    0    0    0    0
            4          0    0    0    0    0    0    0    0    0    0
            5          0    0    0    0    0    0    0    0    0    0
            6          0    0    0    0    0    0    0    0    0    0
            7          0    0    0    0    0    0    0    0    0    0
            8          0    0    0    0    0    0    0    0    0    0
            9          0    0    0    0    0    0    0    0    0    0
            10         0    0    0    0    0    0    0    0    0    0
            11         0    0    0    0    0    0    0    0    0    0
            12         0    0    0    0    0    0    0    0    0    0
            13         0    0    0    0    0    0    0    0    0    0
            14         0    0    0    0    0    0    0    0    0    0
            15         0    0    0    0    0    0    0    0    0    0
            16         0    0    0    0    0    0    0    0    0    0
            17         0    0    0    0    0    0    0    0    0    0
            18         0    0    0    0    0    0    0    0    0    0
            19         0    0    0    0    0    0    0    0    0    0
            20         0    0    0    0    0    0    0    0    0    0
            21         0    0    0    0    0    0    0    0    0    0
            22         0    0    0    0    0    0    0    0    0    0
2          -1          0    0    0    0    0    0    0    0    0    0
            1          0    0    0    0    0    0    0    0    0    0
            2          0    0    0    0    0    0    0    0    0    0
            3          0    0    0    0    0    0    0    0    0    0
            4          0    0    0    0    0    0    0    0    0    0
            5          0    0    0    0    0    0    0    0    0    0
            6          0    0    0    0    0    0    0    0    0    0
            7          0    0    0    0    0    0    0    0    0    0
            8          0    0    0    0    0    0    0    0    0    0
3          -1          0    0    0    0    0    0    0    0    0    0
            1        317  379  331  357  328  358  291  356  346  356
            2        333  326  386  297  310  307  324  323  400  352
            3          0    0    0    0    0    0    0    0    0    0
            4          0    0    0    0    0    0    0    0    0    0
            5          0    0    0    0    0    0    0    0    0    0
            6          0    0    0    0    0    0    0    0    0    0
            7          0    0    0    0    0    0    0    0    0    0
4           1          0    0    0    0    0    0    0    0    0    0
            2          0    0    0    0    0    0    0    0    0    0
            3          0    0    0    0    0    0    0    0    0    0
            4          0    0    0    0    0    0    0    0    0    0

[43 rows x 301 columns]

In [41]:
fc_list = df_pivot_all_raw.index.tolist() #seat_floor, seat_col
fc_list[0][0] #n층 n열

bn_list = df_pivot_all_raw.columns.tolist() #seat_block, seat_num
bn_list[0][0] #n블록 n좌석

new_list = [(x[0], y[0], x[1], y[1]) for x in fc_list for y in bn_list]
new_list

dfnew = df[:0].copy()

for i,(f,b,c,n) in enumerate(new_list):
    dfnew.loc[i,:] = -1
    dfnew.loc[i,'seat_floor'] = f
    dfnew.loc[i,'seat_block'] = b
    dfnew.loc[i,'seat_col'] = c
    dfnew.loc[i,'seat_num'] = n

dfcase = pd.concat([df,dfnew])
dfcase

,age,gender,price,ticket_cancel,performance_code,pre_open_date,open_date,genre,place,running_time,...,play_day,tran_rank,seat_floor,seat_block,seat_col,seat_num,discount_name,discount_rate,membership_free,membership_paid
0,50.0,1.0,10000.0,2.0,302.0,1.0,2022-01-15,교향곡,콘서트홀,120.0,...,금요일,13.0,3.0,BOX9,-1.0,10.0,일반,0.0,일반,골드
4,50.0,0.0,180000.0,0.0,897.0,1.0,2022-01-10,독주,콘서트홀,90.0,...,수요일,795.0,1.0,B,12.0,7.0,일반,0.0,일반,무료
5,30.0,1.0,144000.0,2.0,528.0,1.0,2018-11-19,교향곡,콘서트홀,100.0,...,토요일,435.0,1.0,A,2.0,1.0,블루회원 할인,20.0,일반,블루
6,-1.0,-1.0,0.0,0.0,44.0,0.0,2019-10-23,교향곡,콘서트홀,100.0,...,토요일,958.0,3.0,E,4.0,8.0,초대권,100.0,비회원,비회원
7,-1.0,-1.0,0.0,0.0,827.0,1.0,2019-06-02,교향곡,콘서트홀,120.0,...,화요일,12.0,2.0,D,8.0,4.0,초대권,100.0,비회원,비회원
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12938,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1,-1,-1,-1.0,...,-1,-1.0,4.0,N,4.0,11.0,-1,-1.0,-1,-1
12939,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1,-1,-1,-1.0,...,-1,-1.0,4.0,N,4.0,12.0,-1,-1.0,-1,-1
12940,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1,-1,-1,-1.0,...,-1,-1.0,4.0,N,4.0,13.0,-1,-1.0,-1,-1
12941,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1,-1,-1,-1.0,...,-1,-1.0,4.0,N,4.0,14.0,-1,-1.0,-1,-1
12942,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1,-1,-1,-1.0,...,-1,-1.0,4.0,N,4.0,15.0,-1,-1.0,-1,-1

In [43]:
print(len(df))
print(len(dfnew))
print(len(dfcase))

dfnew.to_csv('df_case.csv',index=False)

1096860
12943
1109803

In [45]:
df1 = pd.read_csv("dataset/df_grade_cluster.csv")
df2 = pd.read_csv("df_case.csv")

new = pd.concat([df1,df2])
new

,Unnamed: 0,age,gender,price,ticket_cancel,pre_open_date,open_date,genre,place,running_time,...,seat_num,discount_name,discount_rate,membership_free,membership_paid,price_org,grade,performance_id,cluster,performance_code
0,0.0,50.0,1.0,10000.0,2.0,1.0,2022-01-15,교향곡,콘서트홀,120.0,...,10.0,일반,0.0,일반,골드,10000.0,B,395.0,0.0,NaN
1,1.0,50.0,0.0,180000.0,0.0,1.0,2022-01-10,독주,콘서트홀,90.0,...,7.0,일반,0.0,일반,무료,180000.0,R,407.0,0.0,NaN
2,2.0,30.0,1.0,144000.0,2.0,1.0,2018-11-19,교향곡,콘서트홀,100.0,...,1.0,블루회원 할인,20.0,일반,블루,180000.0,A,26.0,2.0,NaN
3,3.0,50.0,1.0,24000.0,0.0,0.0,2019-10-05,오페라,콘서트홀,120.0,...,5.0,K-lang 멤버십 회원(1인2매),20.0,일반,무료,30000.0,A,150.0,0.0,NaN
4,4.0,-1.0,-1.0,20000.0,2.0,1.0,2022-04-30,교향곡,콘서트홀,110.0,...,3.0,일반,0.0,비회원,비회원,20000.0,A,465.0,2.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12938,NaN,-1.0,-1.0,-1.0,-1.0,-1.0,-1,-1,-1,-1.0,...,11.0,-1,-1.0,-1,-1,NaN,NaN,NaN,NaN,-1.0
12939,NaN,-1.0,-1.0,-1.0,-1.0,-1.0,-1,-1,-1,-1.0,...,12.0,-1,-1.0,-1,-1,NaN,NaN,NaN,NaN,-1.0
12940,NaN,-1.0,-1.0,-1.0,-1.0,-1.0,-1,-1,-1,-1.0,...,13.0,-1,-1.0,-1,-1,NaN,NaN,NaN,NaN,-1.0
12941,NaN,-1.0,-1.0,-1.0,-1.0,-1.0,-1,-1,-1,-1.0,...,14.0,-1,-1.0,-1,-1,NaN,NaN,NaN,NaN,-1.0
12942,NaN,-1.0,-1.0,-1.0,-1.0,-1.0,-1,-1,-1,-1.0,...,15.0,-1,-1.0,-1,-1,NaN,NaN,NaN,NaN,-1.0