In [1]:
import pandas as pd
import import_ipynb
from basic import *

df = pd.read_csv('./dataset/2023bigcontest_advanced_sac.csv')
df.head()

importing Jupyter notebook from basic.ipynb

,age,gender,membership_type_1,membership_type_2,membership_type_3,membership_type_4,membership_type_5,membership_type_6,tran_date,tran_time,play_date,play_st_time,seat,price,ticket_cancel,discount_type,performance_code,pre_open_date,open_date,genre,place,running_time,intermission,member_yn
0,50.0,F,골드,무료,그린,NaN,NaN,NaN,20220114,1512,20220204,2000,3층 BOX9 10,10000,2,일반,302,20220114.0,20220115.0,교향곡,콘서트홀,120,15,Y
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20211003,1550,20211009,2000,1층 7열 5,0,0,초대권,1120,NaN,20210823.0,독주,리사이틀홀,90,15,N
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20220917,1520,20221105,2000,1층 C블록 16열 3,0,0,초대권,2283,20220911.0,20220911.0,독주,IBK챔버홀,80,15,N
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20190630,1132,20190731,2000,1층 2열 3,0,0,초대권,2798,NaN,20190701.0,독주,리사이틀홀,90,15,N
4,50.0,M,무료,NaN,NaN,NaN,NaN,NaN,20220206,1615,20220302,1930,1층 B블록12열 7,180000,0,일반,897,20220109.0,20220110.0,독주,콘서트홀,90,0,Y

In [2]:
df01 = date_preprocess(df, 'tran_date', 'tran_time', 'tran')
df02 = date_preprocess(df01, 'play_date', 'play_st_time', 'play')
df03 = float_to_datetime(df02, ['pre_open_date', 'open_date'])
df04 = discount_type_sep(separate_seat(tran_rank_dense(df03)))
df05 = membership_col_make(labeling(error_member_yn(df04)))

In [5]:
df05.isnull().sum()

age                  1300183
gender                     0
membership_type_1    1299714
membership_type_2    1433215
membership_type_3    1749009
membership_type_4    1890675
membership_type_5    1919586
membership_type_6    1920868
price                      0
ticket_cancel              0
performance_code           0
pre_open_date              0
open_date                340
genre                  25842
place                      0
running_time               0
intermission               0
member_yn                  0
tran                       0
tran_day                   0
play                       0
play_day                   0
tran_rank                  0
seat_floor             59336
seat_block             59336
seat_col              650091
seat_num               59336
discount_name         367382
discount_rate(%)      367382
membership_free            0
membership_paid            0
dtype: int64

In [26]:
df05.query('`place` == "콘서트홀" and `performance_code` == 302 and `discount_rate(%)` == "0"').price.unique()

array([ 10000,  50000, 120000,  90000], dtype=int64)

In [15]:
df05.query('`genre` != `genre`')['performance_code'].unique()

array([ 229, 2818,  352, 1221, 2816, 2819,  988, 2215,   47,  588,  852,
       1405, 2937,  354, 2472, 1751], dtype=int64)

In [19]:
df05.performance_code.nunique()

2931

In [20]:
df05

,age,gender,membership_type_1,membership_type_2,membership_type_3,membership_type_4,membership_type_5,membership_type_6,price,ticket_cancel,performance_code,pre_open_date,open_date,genre,place,running_time,intermission,member_yn,tran,tran_day,play,play_day,tran_rank,seat_floor,seat_block,seat_col,seat_num,discount_name,discount_rate(%),membership_free,membership_paid
0,50.0,1,골드,무료,그린,NaN,NaN,NaN,10000,2,302,1,2022-01-15,교향곡,콘서트홀,120,15,1,2022-01-14 15:12:00,금요일,2022-02-04 20:00:00,금요일,13.0,3,BOX9,NaN,10,일반,0,일반,골드
1,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,0,0,1120,0,2021-08-23,독주,리사이틀홀,90,15,0,2021-10-03 15:50:00,일요일,2021-10-09 20:00:00,토요일,22.0,1,,7,5,초대권,100,비회원,비회원
2,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,0,0,2283,1,2022-09-11,독주,IBK챔버홀,80,15,0,2022-09-17 15:20:00,토요일,2022-11-05 20:00:00,토요일,62.0,1,C,NaN,16,초대권,100,비회원,비회원
3,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,0,0,2798,0,2019-07-01,독주,리사이틀홀,90,15,0,2019-06-30 11:32:00,일요일,2019-07-31 20:00:00,수요일,2.0,1,,2,3,초대권,100,비회원,비회원
4,50.0,0,무료,NaN,NaN,NaN,NaN,NaN,180000,0,897,1,2022-01-10,독주,콘서트홀,90,0,1,2022-02-06 16:15:00,일요일,2022-03-02 19:30:00,수요일,795.0,1,B,12,7,일반,0,일반,무료
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1920863,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,0,0,1265,1,2019-05-31,실내악,IBK챔버홀,100,15,0,2019-06-14 09:20:00,금요일,2019-07-06 14:00:00,토요일,2.0,1,A,NaN,14,초대권,100,비회원,비회원
1920864,20.0,1,무료,싹틔우미,NaN,NaN,NaN,NaN,21000,0,313,0,2022-12-23,교향곡,콘서트홀,120,0,1,2022-12-24 12:23:00,토요일,2023-04-08 17:00:00,토요일,97.0,3,B,5,4,기타,72430,싹틔우미,무료
1920865,50.0,1,블루,무료,그린,NaN,NaN,NaN,24000,0,736,0,2021-05-03,독주,리사이틀홀,100,15,1,2021-06-14 01:29:00,월요일,2021-06-19 20:00:00,토요일,29.0,1,,7,3,기타,20,일반,블루
1920866,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,0,0,1920,1,2021-10-29,독주,IBK챔버홀,90,15,0,2021-11-23 16:17:00,화요일,2021-11-27 20:00:00,토요일,38.0,1,B,NaN,9,초대권,100,비회원,비회원
1920867,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,0,0,1995,0,2021-05-17,실내악,IBK챔버홀,100,15,0,2021-05-27 17:15:00,목요일,2021-06-19 20:00:00,토요일,8.0,1,B,NaN,3,초대권,100,비회원,비회원